image: node:8.16.0

stages:
  - deploy

before_script:
    - npm install -g serverless
    - bash gitlab-ci-install.sh

deploy to develop:
  only:
    - develop
  stage: deploy
  script:
    - bash gitlab-ci-deploy.sh dev us-east-1
  environment: dev

deploy to master:
  only:
    - master
  stage: deploy
  script:
    - bash gitlab-ci-install.sh prod us-east-1
  environment: prod